_cfg = _cfg or {}
require("share/config/achievement")
require("share/config/afk")
require("share/config/afkRandom")
require("share/config/cmd")
require("share/config/effect")
require("share/config/equip")
require("share/config/equipLevelUp")
require("share/config/equipLib")
require("share/config/goods")
require("share/config/goodsLib")
require("share/config/goodsReward")
require("share/config/language")
require("share/config/monster")
require("share/config/monsterLib")
require("share/config/level")
require("share/config/homeLevelUp")
require("share/config/redirectPage")

require("share/const/pkgAchievementCfgMgr")
require("share/const/pkgAFKCfgMgr")
require("share/const/pkgEquipCfgMgr")
require("share/const/pkgGoodsCfgMgr")
require("share/const/pkgHomeCfgMgr")
require("share/const/pkgLevelCfgMgr")
require("share/const/pkgRewardCfgMgr")

print("config ======================================= load")